using BitcoinUtilities.Node.Services.Headers;

namespace BitcoinUtilities.Node.Events
{
    /// <summary>
    /// This event is generated by <see cref="Blockchain"/> to inform other services that the best head is changed.
    /// </summary>
    public class BestHeadChangedEvent
    {
    }
}