using BitcoinUtilities.Node.Services.Headers;
using BitcoinUtilities.Node.Services.Outputs;

namespace BitcoinUtilities.Node.Events
{
    /// <summary>
    /// This event is generated by <see cref="UtxoUpdateService"/> to inform other services that the UTXO set is changed.
    /// </summary>
    public class UtxoChangedEvent
    {
        public UtxoChangedEvent(DbHeader lastHeader)
        {
            LastHeader = lastHeader;
        }

        public DbHeader LastHeader { get; }
    }
}