using BitcoinUtilities.Node.Modules.Outputs;
using BitcoinUtilities.Threading;

namespace BitcoinUtilities.Node.Events
{
    /// <summary>
    /// This event is generated by <see cref="UtxoUpdateService"/> to inform other services that the UTXO set is changed.
    /// </summary>
    public class UtxoChangedEvent : IEvent
    {
        public UtxoChangedEvent(byte[] lastHeaderHash, int lastHeaderHeight)
        {
            LastHeaderHash = lastHeaderHash;
            LastHeaderHeight = lastHeaderHeight;
        }

        public byte[] LastHeaderHash { get; }
        public int LastHeaderHeight { get; }
    }
}